title: CSE 110 SP26 Team 02's Project
description: A site showcasing our project.
theme: just-the-docs

url: https://cse110-sp26-group02.github.io/cse110-sp26-project-site/

aux_links:
  Template Repository: https://github.com/cse110-sp26-group02/cse110-sp26-project-site/tree/main
